### ISSUE TITLE
[BUG]Items will disappear when two small boxes are merged into one big box

### ISSUE THREAD

**Issue by CuleSKY** [ShaneBeeStudios/SurvivalPlus#13]
**Describe the bug**
Items will disappear when two small boxes are merged into one big box and items will disappear when Creeper destroys the container

**To Reproduce**
When I put any item into a small box, and then merge the small box into a large box, the item will disappear.
When creeper destroys the container, items will disappear.

**Expected behavior**
I have hardly modified the config, and no problems were found when I checked again

**Screenshots/Errors**
NO

**Version Info:**
 - **Plugin Version:** 3.12.4
 - **Server Version/Platform** Akarin 1.15.2（Paper）

**Additional context**
No

**Comment by ShaneBeee** [comment]
I can not replicate this issue.

Steps I tried:
- I placed down a chest
- I put bee keeper boats in the chest
- I put a chest beside
- Opened up the chest and the boots are still there.

**Comment by ShaneBeee** [comment]
Closing!
- Could not replicate the issue
- No response in a while.
