### ISSUE TITLE
[BUG] Netherite pickaxe

### ISSUE THREAD

**Issue by Pistakkio** [ShaneBeeStudios/SurvivalPlus#14]
**Describe the bug**
if I break a block of stone with netherite picaxe the plugin tells me that i need a pickaxe for break it

**To Reproduce**
-place stone
-take netherite pickaxe
-try to break stone

**Expected behavior**
that the blockage broke

**Version Info:**
 - **Plugin Version:** 3.12.2
 - **Server Version/Platform** 1.16.1

**Comment by ShaneBeee** [comment]
I really shouldn't have to ask people to update their plugins before reporting issues.

**Comment by Pistakkio** [comment]
add some "new update available" xD sorry
