### ISSUE TITLE
[BUG] Ender Giant Blade disappear when used.

### ISSUE THREAD

**Issue by Pistakkio** [ShaneBeeStudios/SurvivalPlus#15]
**Describe the bug**
if i use right click with the Ender Giant Blade, after 5/6 minutes it disappear

**To Reproduce**
use the Ender Giant Blade for all night

**Expected behavior**
-craft Ender Giant Blade
-use the Ender Giant Blade with right click anything in the second hand

**Screenshots/Errors**
Youtube video: https://youtu.be/dVkf9jHtSGg

idk if it's a bug... but idk how to fix.

**Version Info:**
 - **Plugin Version:** 3.12.4
 - **Server Version/Platform** PaperMC 1.16.1

**Comment by ShaneBeee** [comment]
When this happens, are there any errors??

**Comment by Pistakkio** [comment]
no errors... disappears for no reason
