### ISSUE TITLE
Additional Commands to refill Energy and maybe add to salts?

### ISSUE THREAD

**Issue by Ellendyra** [ShaneBeeStudios/SurvivalPlus#19]
**Is your feature request related to a problem? Please describe:**
I would like a command to refill your energy bar without sleeping. It would also be nice if you made commands to refill your salts as well, but I'm mainly concerned with the energy bar. We have the "Brewery" plugin which allows you to brew custom drinks such as alcohol or coffee and it would be nice if the coffee they could brew could actually refill their energy. Teas to give you vitamins would be nice too.

**Describe the solution you'd like:**
Just a simple command to add, or subtract energy and possibly salts.

**Describe alternatives you've considered:**
Using the existing survivalplus heal command only gets you so far previously it would reset your salts to a likely lower level. ATM it just seems to bring you to a certain level and not change it if you are above it. Which is nice, but doesn't allow for what I'd like to do.

**Additional context:**

**Comment by ShaneBeee** [comment]
~~We're you really just going to ignore the template and provide absolutely ZERO information/details?~~

Nevermind, I realized what happened, ill edit your issue
