### ISSUE TITLE
About FireStriker's animation

### ISSUE THREAD

**Issue by Pau1am** [ShaneBeeStudios/SurvivalPlus#2]
**Describe the bug**
When I put some smeltable items into the firestriker to smelt, the GUI does not display the normal smelting animation

**To Reproduce**
1.Open firestriker's smelting GUI
2.Put items that can be smelted in
3.No normal animation display

**Expected behavior**
It should be like the animation effect of furnace burning, and it will appear in the right slot after the smelting of the item is completed.

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/41251296/80808616-7cc73d00-8bf2-11ea-98b6-e18eefcab6ee.png)

**Version Info:**
 - **Plugin Version:** 3.11.2
 - **Server Version/Platform** Paper 1.15.2

**Additional context**
Nothing

**Comment by ShaneBeee** [comment]
This isn't a bug, this is intended. Its not easy to add an animation.
In the future I may add an animation so ill mark this as an enhancement.

**Comment by Pau1am** [comment]
It turns out that it seems that I misunderstood. If this is the case, I think that after I put the item I want to smelt in, I should show the smelted item in the right slot. Because many players think that this is the animation loading problem of the plug-in and ask me how to solve it, I also feel very helpless

**Comment by ShaneBeee** [comment]
After a long awaited time, I have finally gotten around to this: https://github.com/ShaneBeeStudios/SurvivalPlus/commit/b99d6ba249417881b527562c7c481a6136f665ad

**Comment by ShaneBeee** [comment]
Changed in 3.14.0
