### ISSUE TITLE
[BUG]Gold equipment will not cause slowdown

### ISSUE THREAD

**Issue by Pau1am** [ShaneBeeStudios/SurvivalPlus#8]
**Describe the bug**
I know this plug-in will slow down when I wear iron or diamond gear, but it does n’t seem to slow down players wearing gold armor.

**To Reproduce**
1.Create a piece of gold equipment in craft_table, such as gold leggings
2.Put it on, you will find that you are not affected by the slowdown

**Expected behavior**
It stands to reason that gold equipment should have the same slowdown effect as iron or diamond equipment

**Screenshots/Errors**
Nothing

**Version Info:**
 - **Plugin Version:** 3.12.0
 - **Server Version/Platform** Paper 1.15.2

**Additional context**
Nothing

**Comment by ShaneBeee** [comment]
I wouldn't exactly call this a bug. This was due to how the plugin was originally written, overriding golden materials.
I will mark this as an enchantment.
